<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://ws.hulkstore.todo1.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://ws.hulkstore.todo1.com" xmlns:intf="http://ws.hulkstore.todo1.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://ws.hulkstore.todo1.com" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="ingresarProducto">
    <complexType/>
   </element>
   <element name="ingresarProductoResponse">
    <complexType/>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="ingresarProductoRequest">

      <wsdl:part element="impl:ingresarProducto" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="ingresarProductoResponse">

      <wsdl:part element="impl:ingresarProductoResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="WSService">

      <wsdl:operation name="ingresarProducto">

         <wsdl:input message="impl:ingresarProductoRequest" name="ingresarProductoRequest">

       </wsdl:input>

         <wsdl:output message="impl:ingresarProductoResponse" name="ingresarProductoResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="WSServiceSoapBinding" type="impl:WSService">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="ingresarProducto">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="ingresarProductoRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="ingresarProductoResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="WSServiceService">

      <wsdl:port binding="impl:WSServiceSoapBinding" name="WSService">

         <wsdlsoap:address location="http://localhost:8080/HulkStore/services/WSService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
